server:
  port: 80

spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:p6spy:mysql://123.57.177.22:3306/dx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8




mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml